services:
  pihole:
    image: pihole/pihole:latest
    ports: 
      - "53:53/tcp"
      - "53:53/udp"
      - "90:80/tcp"
    environment:
      TZ: Europe/Paris
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      FTLCONF_dns_upstreams: unbound;212.27.40.240;212.27.40.241
      FTLCONF_dns_listeningMode: all
    cap_add:
      - NET_ADMIN
      - CAP_SYS_TIME
      - CAP_SYS_NICE
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=le"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^(https?://[^/]+)/?$$"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=$${1}/admin/"
      - "traefik.http.routers.pihole.middlewares=pihole-redirect"
    networks:
      - traefik
      - default

  unbound:
    image: mvance/unbound:latest
    ports:
      - "5335:53"
    volumes:
      - './unbound-config:/opt/ubound/etc/unbound'
    restart: unless-stopped

networks:
  traefik:
    external: true
